#!/usr/bin/env node
/**
 * Bundle the DLP module for the browser demo.
 * Outputs demo/web/bundle.js — a single self-contained IIFE that exposes
 * `globalThis.AiProxyDemo` with the minimal API the page needs.
 *
 * Also writes demo/web/chat-config.js from OMC_DEMO_* env vars, so the live
 * chat page (chat.html) gets its proxy URL / bearer token / model defaults
 * baked in at build time. Override via the in-page Settings panel.
 *
 * Environment variables (all optional):
 *   OMC_DEMO_PROXY_URL      Default proxy origin (e.g. http://127.0.0.1:11500)
 *   OMC_DEMO_BEARER_TOKEN   Bearer token for the proxy auth lane
 *   OMC_DEMO_MODEL          Anthropic model id (e.g. claude-sonnet-4-5)
 *   OMC_DEMO_MAX_TOKENS     Default max_tokens (integer)
 *   OMC_DEMO_SYSTEM_PROMPT  Default system prompt
 */

import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

await build({
  entryPoints: [resolve(here, "entry.ts")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  outfile: resolve(here, "bundle.js"),
  minify: true,
  sourcemap: false,
  legalComments: "none",
  // node-sql-parser and @ast-grep/napi are referenced only via `import type`
  // in dlp.ts, but we mark them external defensively in case esbuild can't
  // erase a type-only import on its own.
  external: ["node-sql-parser", "@ast-grep/napi"],
  banner: {
    js: "/* @duongbkak55/ai-proxy demo bundle — generated by demo/web/build.mjs */",
  },
});

console.log("[demo/web] bundle.js built");

const chatConfig = {
  proxyUrl: process.env.OMC_DEMO_PROXY_URL ?? "",
  bearerToken: process.env.OMC_DEMO_BEARER_TOKEN ?? "",
  model: process.env.OMC_DEMO_MODEL ?? "",
  defaultMaxTokens: process.env.OMC_DEMO_MAX_TOKENS
    ? parseInt(process.env.OMC_DEMO_MAX_TOKENS, 10) || undefined
    : undefined,
  system: process.env.OMC_DEMO_SYSTEM_PROMPT ?? "",
};
const chatConfigJs =
  "/* generated by demo/web/build.mjs from OMC_DEMO_* env vars at build time. */\n" +
  "window.AI_PROXY_DEMO_CONFIG = " +
  JSON.stringify(chatConfig, null, 2) +
  ";\n";
writeFileSync(resolve(here, "chat-config.js"), chatConfigJs);
console.log(
  `[demo/web] chat-config.js written (proxy=${chatConfig.proxyUrl || "(unset)"}, model=${chatConfig.model || "(default)"}, token=${chatConfig.bearerToken ? "set" : "unset"})`,
);
