#!/usr/bin/env node
/**
 * Bundle the DLP module for the browser demo.
 * Outputs demo/web/bundle.js — a single self-contained IIFE that exposes
 * `globalThis.AiProxyDemo` with the minimal API the page needs.
 */

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

await build({
  entryPoints: [resolve(here, "entry.ts")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  outfile: resolve(here, "bundle.js"),
  minify: true,
  sourcemap: false,
  legalComments: "none",
  // node-sql-parser and @ast-grep/napi are referenced only via `import type`
  // in dlp.ts, but we mark them external defensively in case esbuild can't
  // erase a type-only import on its own.
  external: ["node-sql-parser", "@ast-grep/napi"],
  banner: {
    js: "/* @duongbkak55/ai-proxy demo bundle — generated by demo/web/build.mjs */",
  },
});

console.log("[demo/web] bundle.js built");
